const title = 'VUE组件库';
const content = `<h2>UI组件</h2>
<ul>
<li><a href="https://github.com/ElemeFE/element">element</a> ★13489 - 饿了么出品的Vue2的web UI工具套件</li>
<li><a href="https://github.com/airyland/vux">Vux</a> ★8133 - 基于Vue和WeUI的组件库</li>
<li><a href="https://github.com/iview/iview">iview</a> ★6634 - 基于 Vuejs 的开源 UI 组件库</li>
<li><a href="https://github.com/ElemeFE/mint-ui">mint-ui</a> ★6253 - Vue 2的移动UI元素</li>
<li><a href="https://github.com/museui/muse-ui">muse-ui</a> ★3705 - 三端样式一致的响应式 UI 库</li>
<li><a href="https://github.com/marcosmoura/vue-material">vue-material</a> ★3328 - 通过Vue Material和Vue 2建立精美的app应用</li>
<li><a href="https://github.com/vuetifyjs/vuetify">vuetify</a> ★2925 - 为移动而生的Vue JS 2组件框架</li>
<li><a href="https://github.com/JosephusPaye/Keen-UI">Keen-UI</a> ★2749 - 轻量级的基本UI组件合集</li>
<li><a href="https://github.com/wangdahoo/vonic">vonic</a> ★1913 - 快速构建移动端单页应用</li>
<li><a href="https://github.com/monterail/vue-multiselect">vue-multiselect</a> ★1539 - Vue.js选择框解决方案</li>
<li><a href="https://github.com/egoist/eme">eme</a> ★1529 - 优雅的Markdown编辑器</li>
<li><a href="https://github.com/taylorchen709/vueAdmin">vueAdmin</a> ★1455 - 基于vuejs2和element的简单的管理员模板</li>
<li><a href="https://github.com/pi0/bootstrap-vue">bootstrap-vue</a> ★1267 - 应用于Vuejs2的Twitter的Bootstrap 4组件</li>
<li><a href="https://github.com/David-Desmaisons/Vue.Draggable">Vue.Draggable</a> ★1191 - 实现拖放和视图模型数组同步</li>
<li><a href="https://github.com/Zulko/eagle.js">eagle.js</a> ★1128 - hacker的幻灯片演示框架</li>
<li><a href="https://github.com/surmon-china/vue-awesome-swiper">vue-awesome-swiper</a> ★1012 - vue.js触摸滑动组件</li>
<li><a href="https://github.com/ratiw/vue-table">vue-table</a> ★1009 - 简化数据表格</li>
<li><a href="https://github.com/Coffcer/vue-chat">vue-chat</a> ★859 - vuejs和vuex及webpack的聊天示例</li>
<li><a href="https://github.com/chenz24/vue-blu">vue-blu</a> ★850 - 帮助你轻松创建web应用</li>
<li><a href="https://github.com/hilongjw/vue-recyclerview">vue-recyclerview</a> ★849 - 管理大列表的vue-recyclerview</li>
<li><a href="https://github.com/OYsun/VueCircleMenu">VueCircleMenu</a> ★838 - 漂亮的vue圆环菜单</li>
<li><a href="https://github.com/ElemeFE/vue-infinite-scroll">vue-infinite-scroll</a> ★779 - VueJS的无限滚动指令</li>
<li><a href="https://github.com/rafaelpimpa/buefy">buefy</a> ★755 - 响应式UI组件轻量级库</li>
<li><a href="https://github.com/FE-Driver/vue-beauty">vue-beauty</a> ★749 - 由vue和ant design创建的优美UI组件</li>
<li><a href="https://github.com/MopTym/vue-waterfall">vue-waterfall</a> ★737 - Vue.js的瀑布布局组件</li>
<li><a href="https://github.com/luojilab/radon-ui">radon-ui</a> ★715 - 快速开发产品的Vue组件库</li>
<li><a href="https://github.com/lookstudios/vue-loop">vue-loop</a> ★701 - 无限的内容循环</li>
<li><a href="https://github.com/apertureless/vue-chartjs">vue-chartjs</a> ★694 - vue中的Chartjs的封装</li>
<li><a href="https://github.com/myronliu347/vue-carbon">vue-carbon</a> ★684 - 基于 vue 开发MD风格的移动端</li>
<li><a href="https://github.com/vuejs/vue-syntax-highlight">vue-syntax-highlight</a> ★655 - Sublime Text语法高亮</li>
<li><a href="https://github.com/Justineo/vue-echarts">vue-echarts</a> ★649 - VueJS的ECharts组件</li>
<li><a href="https://github.com/surmon-china/vue-quill-editor">vue-quill-editor</a> ★615 - 基于Quill适用于Vue2的富文本编辑器</li>
<li><a href="https://github.com/ElemeFE/vue-amap">vue-amap</a> ★571 - 基于Vue 2和高德地图的地图组件</li>
<li><a href="https://github.com/jinzhe/vue-calendar">vue-calendar</a> ★536 - 日期选择插件</li>
<li><a href="https://github.com/PeachScript/vue-infinite-loading">vue-infinite-loading</a> ★501 - VueJS的无限滚动插件</li>
<li><a href="https://github.com/ElemeFE/vue-swipe">vue-swipe</a> ★481 - VueJS触摸滑块</li>
<li><a href="https://github.com/microzz/vue-music-player">vue-music-player</a> ★451 - Vuejs写一个音乐播放器</li>
<li><a href="https://github.com/wangdahoo/vue-scroller">vue-scroller</a> ★444 - Vonic UI的功能性组件</li>
<li><a href="https://github.com/hilongjw/vue-datepicker">vue-datepicker</a> ★436 - 日历和日期选择组件</li>
<li><a href="https://github.com/Vanthink-UED/vue-core-image-upload">vue-core-image-upload</a> ★393 - 轻量级的vue上传插件</li>
<li><a href="https://github.com/hilongjw/vue-progressbar">vue-progressbar</a> ★379 - vue轻量级进度条</li>
<li><a href="https://github.com/Zhangdroid/Gokotta">Gokotta</a> ★375 - 简单的音乐播放器</li>
<li><a href="https://github.com/sagalbot/vue-sortable">vue-sortable</a> ★373 - 轻松添加拖拽排序</li>
<li><a href="https://github.com/alessiomaffeis/vue-picture-input">vue-picture-input</a> ★352 - 移动友好的图片文件输入组件</li>
<li><a href="https://github.com/xlsdg/vue-echarts-v3">vue-echarts-v3</a> ★351 - VueJS组件封装</li>
<li><a href="https://github.com/jrainlau/markcook">markcook</a> ★343 - 好看的markdown编辑器</li>
<li><a href="https://github.com/surmon-china/vue-video-player">vue-video-player</a> ★336 - VueJS视频及直播播放器</li>
<li><a href="https://github.com/GuillaumeLeclerc/vue-google-maps">vue-google-maps</a> ★334 - 带有双向数据绑定Google地图组件</li>
<li><a href="https://github.com/QingWei-Li/vue-trend">vue-trend</a> ★332 - 简单优雅的星光线条</li>
<li><a href="https://github.com/charliekassel/vuejs-datepicker">vuejs-datepicker</a> ★314 - vue日期选择器组件</li>
<li><a href="https://github.com/Wanderxx/vue-fullcalendar">vue-fullcalendar</a> ★313 - 基于vue.js的全日历组件</li>
<li><a href="https://github.com/PeakTai/vue-html5-editor">vue-html5-editor</a> ★303 - html5所见即所得编辑器</li>
<li><a href="https://github.com/lian-yue/vue-upload-component">vue-upload-component</a> ★298 - Vuejs文件上传组件</li>
<li><a href="https://github.com/SimonZhangITer/DataVisualization">DataVisualization</a> ★298 - 数据可视化</li>
<li><a href="https://github.com/matfish2/vue-tables-2">vue-tables-2</a> ★291 - 显示数据的bootstrap样式网格</li>
<li><a href="https://github.com/OYsun/VueStar">VueStar</a> ★270 - 带星星动画的vue点赞按钮</li>
<li><a href="https://github.com/njleonzhang/vue-data-tables">vue-data-tables</a> ★266 - VueJS2数据表格</li>
<li><a href="https://github.com/TahaSh/vue-paginate">vue-paginate</a> ★261 - 分页数据的简约VueJS插件</li>
<li><a href="https://github.com/ydcss/vue-ydui">vue-ydui</a> ★247 - 基于Vue2的移动端和微信UI</li>
<li><a href="https://github.com/egoist/vue-mugen-scroll">vue-mugen-scroll</a> ★239 - 无限滚动组件</li>
<li><a href="https://github.com/Akryum/vue-virtual-scroller">vue-virtual-scroller</a> ★238 - 带任意数目数据的顺畅的滚动</li>
<li><a href="https://github.com/icai/vue2-calendar">vue2-calendar</a> ★236 - 支持lunar和日期事件的日期选择器</li>
<li><a href="https://github.com/rowanwins/vue-dropzone">vue-dropzone</a> ★233 - 用于文件上传的Vue组件</li>
<li><a href="https://github.com/Awheat/vue2-douban-market">vue2-douban-market</a> ★233 - 仿豆瓣市集webapp项目</li>
<li><a href="https://github.com/euvl/vue-js-modal">vue-js-modal</a> ★228 - 移动友好的Vuejs2的modal</li>
<li><a href="https://github.com/warpcgd/vue-slider">vue-slider</a> ★224 - vue 滑动组件</li>
<li><a href="https://github.com/Haixing-Hu/vue-datetime-picker">vue-datetime-picker</a> ★224 - 日期时间选择控件</li>
<li><a href="https://github.com/ccforward/rubik">rubik</a> ★217 - 基于Vuejs2的开源 UI 组件库</li>
<li><a href="https://github.com/coderdiaz/vue-datasource">vue-datasource</a> ★210 - 创建VueJS动态表格</li>
<li><a href="https://github.com/dai-siki/vue-image-crop-upload">vue-image-crop-upload</a> ★205 - vue图片剪裁上传组件</li>
<li><a href="https://github.com/hifarer/Vueditor">Vueditor</a> ★204 - 所见即所得的编辑器</li>
<li><a href="https://github.com/mint-ui/mint-loadmore">mint-loadmore</a> ★203 - VueJS的双向下拉刷新组件</li>
<li><a href="https://github.com/NightCatSama/vue-slider-component">vue-slider-component</a> ★202 - 在vue1和vue2中使用滑块</li>
<li><a href="https://github.com/microzz/vue-chat">vue-chat</a> ★200 - Vue全家桶+Socket.io+Express/Koa2打造一个智能聊天室</li>
<li><a href="https://github.com/hinesboy/mavonEditor">mavonEditor</a> ★179 - 基于Vue的markdown编辑器</li>
<li><a href="https://github.com/Wlada/vue-carousel-3d">vue-carousel-3d</a> ★173 - VueJS的3D轮播组件</li>
<li><a href="https://github.com/Dafrok/vue-baidu-map">vue-baidu-map</a> ★170 - 基于 Vue 2的百度地图组件库</li>
<li><a href="https://github.com/adeptoas/sweet-modal-vue">sweet-modal-vue</a> ★170 - 精美的点击提示对话框</li>
<li><a href="https://github.com/creotip/vue-particles">vue-particles</a> ★168 - 粒子背景的vue组件</li>
<li><a href="https://github.com/weilao/vue-swiper">vue-swiper</a> ★167 - 易于使用的滑块组件</li>
<li><a href="https://github.com/F-loat/vue-simplemde">vue-simplemde</a> ★166 - VueJS的Markdown编辑器组件</li>
<li><a href="https://github.com/hilongjw/vue-slide">vue-slide</a> ★161 - vue轻量级滑动组件</li>
<li><a href="https://github.com/Astray-git/vue-dragula">vue-dragula</a> ★157 - 使拖放变得简单</li>
<li><a href="https://github.com/Alex-fun/vue-drag-and-drop-list">vue-drag-and-drop-list</a> ★156 - 创建排序列表的Vue指令</li>
<li><a href="https://github.com/davidroyer/vue2-editor">vue2-editor</a> ★155 - HTML编辑器</li>
<li><a href="https://github.com/hchstera/vue-charts">vue-charts</a> ★152 - 轻松渲染一个图表</li>
<li><a href="https://github.com/LucienLee/vue-data-grid">vue-data-grid</a> ★151 - VueJS复杂桌面交互示例</li>
<li><a href="https://github.com/vuwe/vuwe">vuwe</a> ★150 - 基于微信WeUI所开发的专用于Vue2的组件库</li>
<li><a href="https://github.com/MatteoGabriele/vue-progressive-image">vue-progressive-image</a> ★148 - Vue的渐进图像加载插件</li>
<li><a href="https://github.com/ElemeFE/vue-msgbox">vue-msgbox</a> ★148 - vuejs的消息框</li>
<li><a href="https://github.com/JALBAA/vue-lazyload-img">vue-lazyload-img</a> ★147 - 移动优化的vue图片懒加载插件</li>
<li><a href="https://github.com/hilongjw/vue-dragging">vue-dragging</a> ★146 - 使元素可以拖拽</li>
<li><a href="https://github.com/santiblanko/vue-instant">vue-instant</a> ★143 - 轻松创建自动提示的自定义搜索控件</li>
<li><a href="https://github.com/nicolasbeauvais/vue-social-sharing">vue-social-sharing</a> ★142 - 社交分享组件</li>
<li><a href="https://github.com/littlewin-wang/vue-images">vue-images</a> ★139 - 显示一组图片的lightbox组件</li>
<li><a href="https://github.com/NewDadaFE/vue-impression">vue-impression</a> ★134 - 移动Vuejs2 UI元素</li>
<li><a href="https://github.com/ovenslove/vue-mdEditor">vue-mdEditor</a> ★131 - 基于VUE的markdown文本编辑器</li>
<li><a href="https://github.com/cngu/vue-typer">vue-typer</a> ★130 - 模拟用户输入选择和删除文本的Vue组件</li>
<li><a href="https://github.com/weizhenye/vue-highcharts">vue-highcharts</a> ★130 - HighCharts组件</li>
<li><a href="https://github.com/Akryum/vue-tooltip">vue-tooltip</a> ★129 - 带绑定信息提示的提示工具</li>
<li><a href="https://github.com/MMF-FE/vue-svgicon">vue-svgicon</a> ★127 - 创建svg图标组件的工具</li>
<li><a href="https://github.com/wdfe/wdui">wdui</a> ★124 - 基于Vue2的UI组件库</li>
<li><a href="https://github.com/BosNaufal/vue2-loading-bar">vue2-loading-bar</a> ★118 - 最简单的仿Youtube加载条视图</li>
<li><a href="https://github.com/spatie/vue-tabs-component">vue-tabs-component</a> ★116 - 渲染tabs的Vue组件</li>
<li><a href="https://github.com/hzzly/MagicMusic">MagicMusic</a> ★113 - 不一样的音乐</li>
<li><a href="https://github.com/QingWei-Li/vue-region-picker">vue-region-picker</a> ★111 - 选择中国的省份市和地区</li>
<li><a href="https://github.com/galenyuan/vue-datatable">vue-datatable</a> ★102 - 使用Vuejs创建的DataTableView</li>
<li><a href="https://github.com/Coffcer/vue-loading">vue-loading</a> ★102 - 元素中加载block的Vue指令</li>
<li><a href="https://github.com/chenjiahan/vodal">vodal</a> ★99 - 动画的vue模态</li>
<li><a href="https://github.com/waynecz/vue-img-inputer">vue-img-inputer</a> ★97 - 基于Vue2的图片输入框</li>
<li><a href="https://github.com/hilongjw/vue-video">vue-video</a> ★96 - Vue.js的HTML5视频播放器</li>
<li><a href="https://github.com/surmon-china/vue-touch-ripple">vue-touch-ripple</a> ★95 - vuejs的触摸ripple组件</li>
<li><a href="https://github.com/GeoffZhu/vue-event-calendar">vue-event-calendar</a> ★91 - 简单小巧的事件日历组件</li>
<li><a href="https://github.com/luiguild/v-bar">v-bar</a> ★91 - 虚拟响应跨浏览器滚动条</li>
<li><a href="https://github.com/phoenixwong/vue2-timepicker">vue2-timepicker</a> ★84 - 下拉时间选择器</li>
<li><a href="https://github.com/lokyoung/vuejs-paginate">vuejs-paginate</a> ★80 - 分页VueJS组件</li>
<li><a href="https://github.com/ElemeFE/vue-toast-mobile">vue-toast-mobile</a> ★79 - VueJS的toast插件</li>
<li><a href="https://github.com/weifeiyue/vue-datepicker">vue-datepicker</a> ★78 - 漂亮的Vue日期选择器组件</li>
<li><a href="https://github.com/shhdgit/vue-easy-slider">vue-easy-slider</a> ★77 - Vue 2.x的滑块组件</li>
<li><a href="https://github.com/bkzl/vue-float-label">vue-float-label</a> ★76 - VueJS浮动标签模式</li>
<li><a href="https://github.com/BosNaufal/vue-scrollbar">vue-scrollbar</a> ★76 - 最简单的滚动区域组件</li>
<li><a href="https://github.com/youzan/vant">vant</a> ★74 - 有赞出品的Vue2.0移动UI</li>
<li><a href="https://github.com/arvidkahl/vue-json-tree-view">vue-json-tree-view</a> ★74 - Vue的JSON树视图</li>
<li><a href="https://github.com/staskjs/vue-slick">vue-slick</a> ★73 - 实现流畅轮播框的vue组件</li>
<li><a href="https://github.com/znck/vue-keynote">vue-keynote</a> ★73 - 实现声明性代码幻灯片</li>
<li><a href="https://github.com/phanan/vue-google-signin-button">vue-google-signin-button</a> ★73 - 导入谷歌登录按钮</li>
<li><a href="https://github.com/SinanMtl/vue-rate">vue-rate</a> ★68 - Vue评分组件</li>
<li><a href="https://github.com/moip/awesome-mask">awesome-mask</a> ★67 - 拥有独一无二mask的表单</li>
<li><a href="https://github.com/wyzant-dev/vue-radial-progress">vue-radial-progress</a> ★65 - Vue.js放射性进度条组件</li>
<li><a href="https://github.com/CroudSupport/vue-quill">vue-quill</a> ★65 - vue组件构建quill编辑器</li>
<li><a href="https://github.com/Bubblings/vue-date-picker">vue-date-picker</a> ★63 - VueJS日期选择器组件</li>
<li><a href="https://github.com/Kocisov/coffeebreak">coffeebreak</a> ★62 - 实时编辑CSS组件工具</li>
<li><a href="https://github.com/xaksis/vue-good-wizard">vue-good-wizard</a> ★61 - VueJS 2.x wizard plugin</li>
<li><a href="https://github.com/jkchao/vue-loading">vue-loading</a> ★60 - 使用SVG加载</li>
<li><a href="https://github.com/vue-bulma/datepicker">datepicker</a> ★59 - 基于flatpickr的时间选择组件</li>
<li><a href="https://github.com/lithiumjake/vue-placeholders">vue-placeholders</a> ★58 - 处理占位符图片和乱码</li>
<li><a href="https://github.com/tianyong90/we-vue">we-vue</a> ★55 - Vue2及weui1开发的组件</li>
<li><a href="https://github.com/CroudSupport/vue-fullcalendar">vue-fullcalendar</a> ★55 - vue FullCalendar封装</li>
<li><a href="https://github.com/ankane/vue-chartkick">vue-chartkick</a> ★53 - VueJS一行代码实现优美图表</li>
<li><a href="https://github.com/chengxulvtu/cxlt-vue2-toastr">cxlt-vue2-toastr</a> ★52 - 弹出提示的Vue2组件</li>
<li><a href="https://github.com/formly-js/vue-formly">vue-formly</a> ★51 - VueJS的JS表单</li>
<li><a href="https://github.com/BosNaufal/vue2-autocomplete">vue2-autocomplete</a> ★51 - vue2的自动完成组件</li>
<li><a href="https://github.com/bbonnin/vue-morris">vue-morris</a> ★50 - Vuejs组件封装Morrisjs库</li>
<li><a href="https://github.com/ecomfe/veui">veui</a> ★50 - VueJS百度企业UI</li>
<li><a href="https://github.com/yunfeihuang/vue-components">vue-components</a> ★49 - 移动端UI组件库</li>
<li><a href="https://github.com/craigh411/vue-star-rating">vue-star-rating</a> ★49 - 简单高度自定义的星星评级组件</li>
<li><a href="https://github.com/Ginhing/vue-tagsinput">vue-tagsinput</a> ★48 - 基于VueJS的标签组件</li>
<li><a href="https://github.com/alexqdjay/vue-tabs">vue-tabs</a> ★47 - 多tab页轻型框架</li>
<li><a href="https://github.com/myronliu347/vue-popup-mixin">vue-popup-mixin</a> ★47 - 用于管理弹出框的遮盖层</li>
<li><a href="https://github.com/PygmySlowLoris/vue-ripple-directive">vue-ripple-directive</a> ★45 - 使用Vue指令的Material波纹效果</li>
<li><a href="https://github.com/xyxiao001/vue-cropper">vue-cropper</a> ★42 - 一个简单的vue 的图片裁剪插件</li>
<li><a href="https://github.com/lisiyizu/vue-ztree">vue-ztree</a> ★41 - 用 vue 写的树层级组件</li>
<li><a href="https://github.com/icebob/vue-touch-keyboard">vue-touch-keyboard</a> ★41 - VueJS虚拟键盘组件</li>
<li><a href="https://github.com/fangyongbao/cubeex">cubeex</a> ★40 - 包含一套完整的移动UI</li>
<li><a href="https://github.com/miaolz123/vue-chart">vue-chart</a> ★40 - 强大的高速的vue图表解析</li>
<li><a href="https://github.com/yunyi1895/vue-music-master">vue-music-master</a> ★40 - vue手机端网页音乐播放器</li>
<li><a href="https://github.com/jbaysolutions/vue-bootstrap-table">vue-bootstrap-table</a> ★39 - 可排序可检索的表格</li>
<li><a href="https://github.com/jkchao/vue-emoji">vue-emoji</a> ★39 - 好用的emoji插件</li>
<li><a href="https://github.com/vue-bulma/handsontable">handsontable</a> ★39 - 网页表格组件</li>
<li><a href="https://github.com/matfish2/vue-form-2">vue-form-2</a> ★37 - 全面的HTML表单管理的解决方案</li>
<li><a href="https://github.com/blue0728/vue-area">vue-area</a> ★37 - 省市区三级联动插件</li>
<li><a href="https://github.com/vue-comps/vue-side-nav">vue-side-nav</a> ★37 - 响应式的侧边导航</li>
<li><a href="https://github.com/ShanaMaid/vue-image-scroll">vue-image-scroll</a> ★36 - 仿网易云音乐的vue图片滚动插件</li>
<li><a href="https://github.com/bajian/vue-pull-to-refresh">vue-pull-to-refresh</a> ★35 - Vue2的上拉下拉</li>
<li><a href="https://github.com/mint-ui/mint-indicator">mint-indicator</a> ★35 - VueJS移动加载指示器插件</li>
<li><a href="https://github.com/legeneek/vue-image-clip">vue-image-clip</a> ★34 - 基于vue的图像剪辑组件</li>
<li><a href="https://github.com/loujiayu/vue-material-design">vue-material-design</a> ★34 - Vue MD风格组件</li>
<li><a href="https://github.com/saivarunk/vue-simple-upload">vue-simple-upload</a> ★31 - 简单的VueJS上传组件</li>
<li><a href="https://github.com/vue-bulma/chartjs">chartjs</a> ★29 - Vue Bulma的chartjs组件</li>
<li><a href="https://github.com/darrynten/vue-lazy-background-images">vue-lazy-background-images</a> ★29 - 懒加载背景组件的Vue组件</li>
<li><a href="https://github.com/BosNaufal/vue-ripple">vue-ripple</a> ★29 - 制作谷歌MD风格涟漪效果的Vue组件</li>
<li><a href="https://github.com/suguangwen/vue-scroll">vue-scroll</a> ★27 - vue滚动</li>
<li><a href="https://github.com/gilbitron/laravel-vue-pagination">laravel-vue-pagination</a> ★26 - VueJS分页组件</li>
<li><a href="https://github.com/dai-siki/vue-datepicker-simple">vue-datepicker-simple</a> ★26 - 基于vue的日期选择器</li>
<li><a href="https://github.com/shiye515/vue-m-carousel">vue-m-carousel</a> ★26 - vue 移动端轮播组件</li>
<li><a href="https://github.com/vue-comps/vue-parallax">vue-parallax</a> ★23 - 整洁的视觉效果</li>
<li><a href="https://github.com/JackGit/vue-img-loader">vue-img-loader</a> ★22 - 图片加载UI组件</li>
<li><a href="https://github.com/weibangtuo/vue-tree">vue-tree</a> ★22 - vue树视图组件</li>
<li><a href="https://github.com/aweiu/vue-verify-pop">vue-verify-pop</a> ★22 - 带气泡提示的vue校验插件</li>
<li><a href="https://github.com/Teddy-Zhu/vue-waves">vue-waves</a> ★22 - waves的VueJS版本</li>
<li><a href="https://github.com/Teddy-Zhu/vue-smoothscroll">vue-smoothscroll</a> ★20 - smoothscroll的VueJS版本</li>
<li><a href="https://github.com/xinxingyu/vue-city">vue-city</a> ★19 - 城市选择器</li>
<li><a href="https://github.com/sinchang/vue-laypage">vue-laypage</a> ★17 - 简单的VueJS分页组件</li>
<li><a href="https://github.com/eduardostuart/vue-typewriter">vue-typewriter</a> ★15 - vue组件类型</li>
<li><a href="https://github.com/Treri/vue-ios-alertview">vue-ios-alertview</a> ★14 - iOS7+ 风格的alertview服务</li>
<li><a href="https://github.com/doodlewind/vue-cmap">vue-cmap</a> ★14 - Vue China map可视化组件</li>
<li><a href="https://github.com/yeseason/paco-ui-vue">paco-ui-vue</a> ★12 - PACOUI的vue组件</li>
<li><a href="https://github.com/savokiss/vue-cascading-address">vue-cascading-address</a> ★9 - vue地区选择器</li>
<li><a href="https://github.com/ibufu/dd-vue-component">dd-vue-component</a> ★7 - 订单来了的公共组件库</li>
<li><a href="https://github.com/steven5538/vue-button">vue-button</a> ★5 - Vue按钮组件</li>
</ul>
<h2><a href></a>开发框架</h2>
<ul>
<li><a href="https://github.com/vuejs/vue">vue.js</a> ★56380 - 流行的轻量高效的前端组件化方案</li>
<li><a href="https://github.com/fundon/vue-admin">vue-admin</a> ★4612 - Vue管理面板框架</li>
<li><a href="https://github.com/quasarframework/quasar">quasar</a> ★2353 - 响应式网站和混合移动应用程序</li>
<li><a href="https://github.com/SimulatedGREG/electron-vue">electron-vue</a> ★2085 - Electron及VueJS快速启动样板</li>
<li><a href="https://github.com/PanJiaChen/vue-element-admin">vue-element-admin</a> ★1986 - vue2管理系统模板</li>
<li><a href="https://github.com/egoist/vuepack">vuepack</a> ★1618 - 现代VueJS启动器</li>
<li><a href="https://github.com/N3-components/N3-components">N3-components</a> ★656 - 快速构建页面和应用</li>
<li><a href="https://github.com/honraytech/VueThink">VueThink</a> ★373 - 前后端分离框架</li>
<li><a href="https://github.com/petervmeijgaard/vue-2.0-boilerplate">vue-2.0-boilerplate</a> ★358 - Vue2单页应用样板&#8203;</li>
<li><a href="https://github.com/hanan198501/vue-spa-template">vue-spa-template</a> ★344 - 前后端分离后的单页应用开发</li>
<li><a href="https://github.com/nolimits4web/Framework7-Vue">Framework7-Vue</a> ★283 - VueJS与Framework7结合</li>
<li><a href="https://github.com/wangxg2016/vue-bulma">vue-bulma</a> ★215 - 轻量级高性能MVVM Admin UI框架</li>
<li><a href="https://github.com/andrewcourtice/vuetiful">vuetiful</a> ★189 - 创建业务及管理应用程序</li>
<li><a href="https://github.com/cklmercer/vue-stack-2.0">vue-stack-2.0</a> ★155 - Vue2项目样板</li>
<li><a href="https://github.com/devjin0617/vue2-admin-lte">vue2-admin-lte</a> ★154 - vue2版本的adminLTE</li>
<li><a href="https://github.com/shenghy/jspangAdmin">jspangAdmin</a> ★140 - 基于Vue2的后台管理系统</li>
<li><a href="https://github.com/erguotou520/vue-fullstack">vue-fullstack</a> ★140 - 实时的用户友好的后台系统</li>
<li><a href="https://github.com/cristijora/vue-paper-dashboard">vue-paper-dashboard</a> ★120 - Vue的Tim Paper 仪表盘</li>
<li><a href="https://github.com/rodzzlessa24/vue-webgulp">vue-webgulp</a> ★113 - 仿VueJS Vue loader示例</li>
<li><a href="https://github.com/Metnew/vue-element-starter">vue-element-starter</a> ★83 - vue启动页</li>
<li><a href="https://github.com/yangjiewu/vuemin">vuemin</a> ★17 - 基于Vue的企业级前端开发框架</li>
<li><a href="https://github.com/woleicom/vue-team-template">vue-team-template</a> ★12 - 一种构建vue项目的选择方案</li>
</ul>
<h2><a href></a>实用库</h2>
<ul>
<li><a href="https://github.com/vuejs/vuex">vuex</a> ★8043 - 专为 Vue.js 应用程序开发的状态管理模式</li>
<li><a href="https://github.com/vuejs/vue-loader">vue-loader</a> ★1847 - Vue.js 针对Webpack的组件装载插件</li>
<li><a href="https://github.com/vuejs/vue-validator">vue-validator</a> ★1807 - vue的验证器插件</li>
<li><a href="https://github.com/hilongjw/vue-lazyload">vue-lazyload</a> ★1224 - 用于懒加载的Vue模块</li>
<li><a href="https://github.com/monterail/vuelidate">vuelidate</a> ★1075 - 简单轻量级的基于模块的Vue.js验证</li>
<li><a href="https://github.com/kazupon/vue-i18n">vue-i18n</a> ★1053 - VueJS的多语言切换插件</li>
<li><a href="https://github.com/zerqu/qingcheng">qingcheng</a> ★736 - qingcheng主题</li>
<li><a href="https://github.com/MetinSeylan/Vue-Socket.io">Vue-Socketio</a> ★533 - VueJS的socketio实现</li>
<li><a href="https://github.com/Justineo/vue-awesome">vue-awesome</a> ★532 - VueJS字体Awesome组件</li>
<li><a href="https://github.com/ElemeFE/vue-desktop">vue-desktop</a> ★496 - 创建管理面板网站的UI库</li>
<li><a href="https://github.com/imcvampire/vue-axios">vue-axios</a> ★491 - 将axios整合到VueJS的封装</li>
<li><a href="https://github.com/declandewet/vue-meta">vue-meta</a> ★467 - 管理app的meta信息</li>
<li><a href="https://github.com/ktquez/vue-head">vue-head</a> ★396 - head标签的meta信息操作</li>
<li><a href="https://github.com/Akryum/meteor-vue-component">meteor-vue-component</a> ★382 - vue和meteor整合</li>
<li><a href="https://github.com/eddyerburgh/avoriaz">avoriaz</a> ★338 - VueJS测试实用工具库</li>
<li><a href="https://github.com/LinusBorg/portal-vue">portal-vue</a> ★239 - 在组件外部渲染DOM</li>
<li><a href="https://github.com/jrainlau/vue-flatpickr">vue-flatpickr</a> ★228 - 封装Flatpickr的Vue组件</li>
<li><a href="https://github.com/egoist/vue-timeago">vue-timeago</a> ★195 - VueJS的时间前组件</li>
<li><a href="https://github.com/lyonlai/blessed-vue">blessed-vue</a> ★181 - 编写命令行UI的VueJS运行时</li>
<li><a href="https://github.com/wrseward/vue-unit">vue-unit</a> ★179 - 创建单元测试组件</li>
<li><a href="https://github.com/dgrubelic/vue-authenticate">vue-authenticate</a> ★177 - 简单的VueJS身份认证库</li>
<li><a href="https://github.com/rigor789/vue-scrollTo">vue-scrollTo</a> ★174 - 滚动到元素的VueJS指令</li>
<li><a href="https://github.com/cenkai88/vue-svg-icon">vue-svg-icon</a> ★157 - vue2的可变彩色svg图标方案</li>
<li><a href="https://github.com/simplesmiler/vue-focus">vue-focus</a> ★148 - 可重用VueJS组件的焦点指令</li>
<li><a href="https://github.com/zhouzhuojie/meteor-vue">meteor-vue</a> ★134 - VueJS和Meteor的桥接</li>
<li><a href="https://github.com/lynzz/element-admin">element-admin</a> ★130 - 支持 vuecli 的 Element UI 的后台模板</li>
<li><a href="https://github.com/QingWei-Li/vuep">vuep</a> ★118 - 用实时编辑和预览来渲染Vue组件</li>
<li><a href="https://github.com/medevicex/vuet">vuet</a> ★116 - 一个跨页面、跨组件的状态管理插件</li>
<li><a href="https://github.com/Coffcer/vue-bootstrap-modal">vue-bootstrap-modal</a> ★112 - vue的Bootstrap样式组件</li>
<li><a href="https://github.com/haydenbbickerton/vue-animate">vue-animate</a> ★106 - 跨浏览器CSS3动画库</li>
<li><a href="https://github.com/kaorun343/vue-property-decorator">vue-property-decorator</a> ★104 - VueJS和属性Decorator</li>
<li><a href="https://github.com/SevenOutman/vue-aplayer">vue-aplayer</a> ★100 - 便于配置的音乐播放器vue2组件</li>
<li><a href="https://github.com/apertureless/vue-password-strength-meter">vue-password-strength-meter</a> ★97 - 交互式密码强度计</li>
<li><a href="https://github.com/icebob/vue-websocket">vue-websocket</a> ★91 - VueJS的Websocket插件</li>
<li><a href="https://github.com/pinguinjkeke/vue-local-storage">vue-local-storage</a> ★88 - 具有类型支持的Vuejs本地储存插件</li>
<li><a href="https://github.com/xtongs/vue-recyclist">vue-recyclist</a> ★88 - vuejs无限滚动列表</li>
<li><a href="https://github.com/yeyuqiudeng/vue-lazy-render">vue-lazy-render</a> ★87 - 用于Vue组件的延迟渲染</li>
<li><a href="https://github.com/superman66/vue-qart">vue-qart</a> ★86 - 用于qartjs的Vue2指令</li>
<li><a href="https://github.com/lmk123/vue-framework7">vue-framework7</a> ★85 - 结合VueJS使用的Framework7组件</li>
<li><a href="https://github.com/kartsims/vue-cordova">vue-cordova</a> ★85 - Cordova的VueJS插件</li>
<li><a href="https://github.com/FranckFreiburger/http-vue-loader">http-vue-loader</a> ★84 - 从html及js环境加载vue文件</li>
<li><a href="https://github.com/apertureless/vue-parallax">vue-parallax</a> ★84 - 快速60fps视差滚动效果组件</li>
<li><a href="https://github.com/xiaokaike/vue-clipboard">vue-clipboard</a> ★84 - VueJS的剪贴板</li>
<li><a href="https://github.com/JiriChara/vue-kindergarten">vue-kindergarten</a> ★83 - 将kindergarten集成到VueJS应用</li>
<li><a href="https://github.com/cklmercer/vue-events">vue-events</a> ★83 - 简化事件的VueJS插件</li>
<li><a href="https://github.com/se-panfilov/vue-notifications">vue-notifications</a> ★80 - 非阻塞通知库</li>
<li><a href="https://github.com/Sopamo/vue-online">vue-online</a> ★77 - reactive的在线和离线组件</li>
<li><a href="https://github.com/iFgR/vue-shortkey">vue-shortkey</a> ★74 - 应用于Vue.js的Vue-ShortKey 插件</li>
<li><a href="https://github.com/yangmingshan/vue-bus">vue-bus</a> ★71 - VueJS的事件总线</li>
<li><a href="https://github.com/dkfbasel/vuex-i18n">vuex-i18n</a> ★71 - 定位插件</li>
<li><a href="https://github.com/wxsms/uiv">uiv</a> ★70 - Vue实现的Bootstrap组件</li>
<li><a href="https://github.com/weinot/vue-router-transition">vue-router-transition</a> ★69 - 页面过渡插件</li>
<li><a href="https://github.com/mlyknown/vue-gesture">vue-gesture</a> ★69 - VueJS的手势事件插件</li>
<li><a href="https://github.com/thetutlage/vue-clip">vue-clip</a> ★67 - 简约的破解文件上传器</li>
<li><a href="https://github.com/SimulatedGREG/vue-electron">vue-electron</a> ★66 - 将选择的API封装到Vue对象中的插件</li>
<li><a href="https://github.com/vue-bulma/cleave">cleave</a> ★64 - 基于cleave.js的Cleave组件</li>
<li><a href="https://github.com/gocanto/vuemit">vuemit</a> ★63 - 处理VueJS事件</li>
<li><a href="https://github.com/israelss/vue-worker">vue-worker</a> ★56 - 使用webworkers的Vue插件</li>
<li><a href="https://github.com/leonardovilarinho/vue-acl">vue-acl</a> ★54 - VueJS访问控制列表插件</li>
<li><a href="https://github.com/HerringtonDarkholme/vue-ts-loader">vue-ts-loader</a> ★54 - 在Vue装载机检查脚本</li>
<li><a href="https://github.com/David-Desmaisons/Vue.resize">Vue.resize</a> ★51 - 检测HTML调整大小事件的vue指令</li>
<li><a href="https://github.com/Vuedeux/vuedeux">vuedeux</a> ★50 - 轻量级开源实用用层</li>
<li><a href="https://github.com/RobinCK/vue-ls">vue-ls</a> ★49 - 适配Vuecontext中LocalStorage的Vue插件</li>
<li><a href="https://github.com/gocanto/lazy-vue">lazy-vue</a> ★48 - 懒加载图片</li>
<li><a href="https://github.com/matfish2/vue-pagination-2">vue-pagination-2</a> ★46 - 简单通用的分页组件</li>
<li><a href="https://github.com/AStaroverov/v-media-query">v-media-query</a> ★44 - vue中添加用于配合媒体查询的方法</li>
<li><a href="https://github.com/Akryum/vue-observe-visibility">vue-observe-visibility</a> ★42 - 当元素在页面上可见或隐藏时检测</li>
<li><a href="https://github.com/Coffcer/vue-lazy-component">vue-lazy-component</a> ★38 - 懒加载组件或者元素的Vue指令</li>
<li><a href="https://github.com/ropbla9/vue-reactive-storage">vue-reactive-storage</a> ★37 - vue插件的Reactive层</li>
<li><a href="https://github.com/miaolz123/vue-helmet">vue-helmet</a> ★37 - HTML标题管理器</li>
<li><a href="https://github.com/richardanaya/voir">voir</a> ★35 - 保持mutation与视图组件的分离</li>
<li><a href="https://github.com/xanf/vuex-shared-mutations">vuex-shared-mutations</a> ★34 - 分享某种Vuex mutations</li>
<li><a href="https://github.com/surmon-china/vue-drag-zone">vue-drag-zone</a> ★28 - 适用于Vue2的dom拖动组件</li>
<li><a href="https://github.com/mysticatea/vue-eslint-parser">vue-eslint-parser</a> ★27 - ESLint自定义解析</li>
<li><a href="https://github.com/vue-bulma/modal">modal</a> ★26 - Vue Bulma的modal组件</li>
<li><a href="https://github.com/wakeupmypig/vue-plan">vue-plan</a> ★25 - Vuex-状态管理</li>
<li><a href="https://github.com/BosNaufal/vue-file-base64">vue-file-base64</a> ★22 - 将文件转换为Base64的vue组件</li>
<li><a href="https://github.com/lzxb/vue-methods-promise">vue-methods-promise</a> ★21 - 使vue方法支持promise</li>
<li><a href="https://github.com/David-Desmaisons/Vue.ImagesLoaded">Vue.ImagesLoaded</a> ★20 - 检测图片加载的VueJS指令</li>
<li><a href="https://github.com/irwansyahwii/Famous-Vue">Famous-Vue</a> ★16 - Famous库的vue组件</li>
<li><a href="https://github.com/LeoHuiyi/leo-vue-validator">leo-vue-validator</a> ★15 - 异步的表单验证组件</li>
<li><a href="https://github.com/Haixing-Hu/vue-titlecase">vue-titlecase</a> ★13 - 用于字符串titlecased的VueJS过滤器</li>
<li><a href="https://github.com/MetinSeylan/Vue-Easy-Validator">Vue-Easy-Validator</a> ★12 - 简单的表单验证</li>
<li><a href="https://github.com/vue-comps/vue-zoombox">vue-zoombox</a> ★12 - 一个高级zoombox</li>
<li><a href="https://github.com/imcvampire/vue-truncate-filter">vue-truncate-filter</a> ★10 - 截断字符串的VueJS过滤器</li>
<li><a href="https://github.com/ElderJames/vue-router-storage">vue-router-storage</a> ★9 - vue历史路由持久化的解决方案</li>
<li><a href="https://github.com/syropian/vue-input-autosize">vue-input-autosize</a> ★9 - 基于内容自动调整文本输入的大小</li>
<li><a href="https://github.com/phphe/vue-data-validator">vue-data-validator</a> ★4 - Vuejs2的数据验证插件</li>
<li><a href="https://github.com/yodfz/vue-lazyloadImg">vue-lazyloadImg</a> ★4 - 图片懒加载插件</li>
</ul>
<h2><a href></a>服务端</h2>
<ul>
<li><a href="https://github.com/nuxt/nuxt.js">nuxt.js</a> ★4564 - 用于服务器渲染Vue app的最小化框架</li>
<li><a href="https://github.com/egoist/unvue">unvue</a> ★310 - 使用简单的通用VueJS应用</li>
<li><a href="https://github.com/danmademe/express-vue">express-vue</a> ★302 - 简单的使用服务器端渲染vue.js</li>
<li><a href="https://github.com/ccforward/vue-ssr">vue-ssr</a> ★92 - 非常简单的VueJS服务器端渲染模板</li>
<li><a href="https://github.com/monkeyWangs/doubanMovie-SSR">doubanMovie-SSR</a> ★85 - Vue豆瓣电影服务端渲染</li>
<li><a href="https://github.com/hilongjw/vue-ssr">vue-ssr</a> ★80 - 结合Express使用Vue2服务端渲染</li>
<li><a href="https://github.com/leaves4j/vue-easy-renderer">vue-easy-renderer</a> ★44 - Nodejs服务端渲染</li>
</ul>
<h2><a href></a>辅助工具</h2>
<ul>
<li><a href="https://github.com/vue-play/vue-play">vue-play</a> ★641 - 展示Vue组件的最小化框架</li>
<li><a href="https://github.com/MiCottOn/DejaVue">DejaVue</a> ★635 - Vuejs可视化及压力测试</li>
<li><a href="https://github.com/OYsun/vscode-VueHelper">vscode-VueHelper</a> ★228 - 目前vscode最好的vue代码提示插件</li>
<li><a href="https://github.com/NetanelBasal/vue-generate-component">vue-generate-component</a> ★56 - 轻松生成Vue js组件的CLI工具</li>
<li><a href="https://github.com/xwpongithub/vue-multipage-cli">vue-multipage-cli</a> ★40 - 简单的多页CLI</li>
<li><a href="https://github.com/MetinSeylan/VuejsStarterKit">VuejsStarterKit</a> ★29 - vuejs starter套件</li>
</ul>
<h2><a href></a>应用实例</h2>
<ul>
<li><a href="https://github.com/phanan/koel">koel</a> ★7773 - 基于网络的个人音频流媒体服务</li>
<li><a href="https://github.com/pagekit/pagekit">pagekit</a> ★4225 - 轻量级的CMS建站系统</li>
<li><a href="https://github.com/lin-xin/vue-manage-system">vue-manage-system</a> ★2057 - 后台管理系统解决方案</li>
<li><a href="https://github.com/Vuedo/vuedo">vuedo</a> ★1265 - 博客平台</li>
<li><a href="https://github.com/jackhutu/jackblog-vue">jackblog-vue</a> ★1120 - 个人博客系统</li>
<li><a href="https://github.com/jcc/blog">PJ Blog</a> ★1018 - 开源博客</li>
<li><a href="https://github.com/lzxb/vue-cnode">vue-cnode</a> ★787 - 重写vue版cnode社区</li>
<li><a href="https://github.com/ericjjj/vms">vms</a> ★629 - vuejs2管理系统</li>
<li><a href="https://github.com/ycwalker/CMS-of-Blog">CMS-of-Blog</a> ★541 - 博客内容管理器</li>
<li><a href="https://github.com/Caiyeon/goldfish">goldfish</a> ★518 - 用于HashiCorp Vault的Admin UI</li>
<li><a href="https://github.com/mrgodhani/rss-reader">rss-reader</a> ★368 - 简单的rss阅读器</li>
<li><a href="https://github.com/viko16/vue-ghpages-blog">vue-ghpages-blog</a> ★254 - 依赖GitHub Pages无需本地生成的静态博客</li>
<li><a href="https://github.com/surmon-china/vue-blog">vue-blog</a> ★143 - 使用Vue2.0 和Vuex的vue-blog</li>
<li><a href="https://github.com/wh469012917/swoole-vue-webim">swoole-vue-webim</a> ★137 - Web版的聊天应用</li>
<li><a href="https://github.com/zhangxin840/tomato5">tomato5</a> ★134 - 实时的协作工具</li>
<li><a href="https://github.com/Angarsk8/Loopa-News">Loopa-News</a> ★133 - 开源社会新闻应用</li>
<li><a href="https://github.com/reg21st/vue2-management-platform">vue2-management-platform</a> ★74 - vue2.0+ elementUI 后台管理平台</li>
<li><a href="https://github.com/thelinuxlich/vue-dashing-js">vue-dashing-js</a> ★70 - nuvo-dashing-js的fork</li>
<li><a href="https://github.com/sapjax/fewords">fewords</a> ★63 - 功能极其简单的笔记本</li>
<li><a href="https://github.com/wxs77577/adminify">adminify</a> ★46 - 一个基于Vuetify material的Admin面板</li>
</ul>
<h2><a href></a>Demo示例</h2>
<ul>
<li><a href="https://github.com/bailicangdu/vue2-elm">vue2-elm</a> ★8036 - 重写饿了么webapp</li>
<li><a href="https://github.com/shinygang/Vue-cnodejs">Vue-cnodejs</a> ★2491 - 基于vue重写Cnodejs.org的webapp</li>
<li><a href="https://github.com/javaSwing/NeteaseCloudWebApp">NeteaseCloudWebApp</a> ★1549 - 高仿网易云音乐的webapp</li>
<li><a href="https://github.com/bailicangdu/vue2-happyfri">vue2-happyfri</a> ★1535 - vue2及vuex的入门练习项目</li>
<li><a href="https://github.com/hilongjw/vue-zhihu-daily">vue-zhihu-daily</a> ★1010 - 知乎日报 with Vuejs</li>
<li><a href="https://github.com/lzxb/vue2-demo">vue2-demo</a> ★994 - 从零构建vue2 + vue-router + vuex 开发环境</li>
<li><a href="https://github.com/useryangtao/vue-wechat">vue-wechat</a> ★939 - vue.js开发微信app界面</li>
<li><a href="https://github.com/liangxiaojuan/eleme">eleme</a> ★882 - 高仿饿了么app商家详情</li>
<li><a href="https://github.com/kenberkeley/vue-demo">vue-demo</a> ★755 - vue简易留言板</li>
<li><a href="https://github.com/lybenson/bilibili-vue">bilibili-vue</a> ★694 - 全栈式开发bilibili首页</li>
<li><a href="https://github.com/codecasts/spa-starter-kit">spa-starter-kit</a> ★646 - 单页应用启动套件</li>
<li><a href="https://github.com/SimonZhangITer/VueDemo_Sell_Eleme">VueDemo_Sell_Eleme</a> ★636 - Vue2高仿饿了么外卖平台</li>
<li><a href="https://github.com/Sioxas/vue-music">vue-music</a> ★621 - Vue 音乐搜索播放</li>
<li><a href="https://github.com/jeneser/douban">douban</a> ★606 - 基于vue全家桶的精致豆瓣DEMO</li>
<li><a href="https://github.com/liangxiaojuan/vue-Meizi">vue-Meizi</a> ★604 - vue最新实战项目</li>
<li><a href="https://github.com/zhengguorong/maizuo">maizuo</a> ★603 - vue/vuex/redux仿卖座网</li>
<li><a href="https://github.com/zhaohaodang/vue-WeChat">vue-WeChat</a> ★558 - 基于Vue2高仿微信App的单页应用</li>
<li><a href="https://github.com/lavyun/vue-demo-kugou">vue-demo-kugou</a> ★500 - vuejs仿写酷狗音乐webapp</li>
<li><a href="https://github.com/bailicangdu/vue2-manage">vue2-manage</a> ★457 - 基于 vue + element-ui 的后台管理系统</li>
<li><a href="https://github.com/yatessss/zhihudaily-vue">zhihudaily-vue</a> ★455 - 知乎日报web版</li>
<li><a href="https://github.com/ShanaMaid/vue-163-music">vue-163-music</a> ★448 - vue仿网易云音乐客户端版</li>
<li><a href="https://github.com/superman66/vue-axios-github">vue-axios-github</a> ★448 - 登录拦截登出功能</li>
<li><a href="https://github.com/jiakeqi/douban">douban</a> ★440 - 模仿豆瓣前端</li>
<li><a href="https://github.com/andylei18/vue-shopping">vue-shopping</a> ★404 - 蘑菇街移动端</li>
<li><a href="https://github.com/canfoo/vue2.0-taopiaopiao">vue2.0-taopiaopiao</a> ★402 - vue2.0与express构建淘票票页面</li>
<li><a href="https://github.com/hzzly/xyy-vue">xyy-vue</a> ★396 - 大学生交流平台</li>
<li><a href="https://github.com/TIGERB/easy-vue">easy-vue</a> ★370 - 使用Vue实现简易web</li>
<li><a href="https://github.com/superman66/vue2.x-douban">vue2.x-douban</a> ★360 - Vue2实现简易豆瓣电影webApp</li>
<li><a href="https://github.com/jiangqizheng/vue2-MiniQQ">vue2-MiniQQ</a> ★351 - 基于Vue2实现的仿手机QQ单页面应用</li>
<li><a href="https://github.com/wendaosanshou/mi-by-vue">mi-by-vue</a> ★291 - VueJS仿小米官网</li>
<li><a href="https://github.com/walleeeee/daily-zhihu">daily-zhihu</a> ★275 - 基于Vue2的知乎日报单页应用</li>
<li><a href="https://github.com/jiangjiu/vue-leancloud-blog">vue-leancloud-blog</a> ★268 - 一个前后端完全分离的单页应用</li>
<li><a href="https://github.com/Reusjs/VueMusic-PC">VueMusic-PC</a> ★260 - Vue.js高还原网易云音乐系列</li>
<li><a href="https://github.com/yjj5855/node-vue-server-webpack">node-vue-server-webpack</a> ★253 - Node.js+Vue.js+webpack快速开发框架</li>
<li><a href="https://github.com/beauty-enjoy/beauty">beauty</a> ★245 - 豆瓣美女clone</li>
<li><a href="https://github.com/liujians/vue-adminLte-vue-router">vue-adminLte-vue-router</a> ★243 - vue和adminLte整合应用</li>
<li><a href="https://github.com/okoala/vue-fis3">vue-fis3</a> ★217 - 流行开源工具集成demo</li>
<li><a href="https://github.com/lin-xin/notepad">notepad</a> ★216 - 本地存储的记事本</li>
<li><a href="https://github.com/ChuckCZC/vue-demo-maizuo">vue-demo-maizuo</a> ★210 - 使用Vue2全家桶仿制卖座电影</li>
<li><a href="https://github.com/Werb/Pixel-Web">Pixel-Web</a> ★198 - 一个 Vue 微博客户端</li>
<li><a href="https://github.com/MengZhaoFly/netease_yanxuan">netease_yanxuan</a> ★198 - vue版网易严选</li>
<li><a href="https://github.com/dmtrbrl/tmdb-app">tmdb-app</a> ★194 - TMDbVueJS应用</li>
<li><a href="https://github.com/xrr2016/vue-express-mongodb">vue-express-mongodb</a> ★189 - 简单的前后端分离案例</li>
<li><a href="https://github.com/iHaPBoy/vue-zhihudaily">vue-zhihudaily</a> ★187 - 知乎日报 Web 版本</li>
<li><a href="https://github.com/RalfZhang/Vdo">Vdo</a> ★179 - VueJS与MD重构豆瓣</li>
<li><a href="https://github.com/BUPT-HJM/vue-blog">vue-blog</a> ★171 - 单用户博客</li>
<li><a href="https://github.com/xiaobinwu/Wuji">Wuji</a> ★168 - 吾记网页版</li>
<li><a href="https://github.com/rokups/hello-vue-django">hello-vue-django</a> ★160 - 使用带有Django的vuejs的样板项目</li>
<li><a href="https://github.com/pomelo-chuan/Zhihu-Daily-Vue.js">Zhihu-Daily-Vue.js</a> ★157 - Vuejs单页网页应用</li>
<li><a href="https://github.com/renjie1996/tencent-sports">tencent-sports</a> ★154 - Vue全家桶仿腾讯体育</li>
<li><a href="https://github.com/zhixuanziben/gouyan-movie-vue">gouyan-movie-vue</a> ★151 - 基于vue的在线电影影讯网站</li>
<li><a href="https://github.com/CommanderXL/x-blog">x-blog</a> ★145 - 开源的个人blog项目</li>
<li><a href="https://github.com/lxyisme/vue-musicApp">vue-musicApp</a> ★132 - 使用vue全家桶制作的音乐播放器</li>
<li><a href="https://github.com/wszgxa/vue-cnode">vue-cnode</a> ★131 - vue单页应用demo</li>
<li><a href="https://github.com/193Eric/webpack-vue-vueRouter">webpack-vue-vueRouter</a> ★130 - webpack及vue开发的简单项目实例</li>
<li><a href="https://github.com/Molunerfinn/vue-koa-demo">vue-koa-demo</a> ★128 - 使用Vue2和Koa1的全栈demo</li>
<li><a href="https://github.com/elva2596/vueBlog">vueBlog</a> ★127 - 前后端分离博客</li>
<li><a href="https://github.com/secreter/websocket_chat">websocket_chat</a> ★127 - 基于vue和websocket的多人在线聊天室</li>
<li><a href="https://github.com/peng1992/houtai">houtai</a> ★125 - 基于vue和Element的后台管理系统</li>
<li><a href="https://github.com/hcy1996/vue-toutiao">vue-toutiao</a> ★121 - vuejs高仿今日头条移动端</li>
<li><a href="https://github.com/microzz/vue-cnode">vue-cnode</a> ★121 - 开源的CNode社区</li>
<li><a href="https://github.com/BosNaufal/vue-mini-shop">vue-mini-shop</a> ★121 - VueJS在线商店</li>
<li><a href="https://github.com/beidan/photoShare">photoShare</a> ★120 - 基于图片分享的社交平台</li>
<li><a href="https://github.com/vanishcode/iview2-management-system">iview2-management-system</a> ★119 - 后台管理系统解决方案简单示例</li>
<li><a href="https://github.com/monkeyWangs/doubanMovie">doubanMovie</a> ★119 - 豆瓣电影展示</li>
<li><a href="https://github.com/hbxywdk/eleme-vue2">eleme-vue2</a> ★112 - 仿饿了么H5纯前端Vue版</li>
<li><a href="https://github.com/cccyb/vue-zhihu-daily">vue-zhihu-daily</a> ★111 - 基于Vue全家桶开发的知乎日报</li>
<li><a href="https://github.com/biaodigit/Vue-News">Vue-News</a> ★107 - 基于vue全家桶的仿知乎日报单页应用</li>
<li><a href="https://github.com/xingbofeng/douban-movie">douban-movie</a> ★107 - 仿豆瓣电影wap端</li>
<li><a href="https://github.com/qxl1231/generator-loopback-vue">generator-loopback-vue</a> ★104 - 典型前后端分离项目模板</li>
<li><a href="https://github.com/odranoelBR/vue-quasar-admin-example">vue-quasar-admin-example</a> ★99 - 将Quasar和VueJS应用于SPA项目</li>
<li><a href="https://github.com/cs1707/vue-zhihudaily-2.0">vue-zhihudaily-2.0</a> ★97 - 使用Vue2.0+vue-router+vuex创建的zhihudaily</li>
<li><a href="https://github.com/liangxiaojuan/vue-todos">vue-todos</a> ★95 - vue最新实战项目教程</li>
<li><a href="https://github.com/ddqre12345/vue-music">vue-music</a> ★91 - 网易云音乐Demo</li>
<li><a href="https://github.com/Panda-Hope/vue-qqmusic">vue-qqmusic</a> ★90 - Vue全家桶+Mint-Ui打造高仿QQMusic</li>
<li><a href="https://github.com/vincentSea/vue2.x-Cnode">vue2.x-Cnode</a> ★88 - 基于vue全家桶的Cnode社区</li>
<li><a href="https://github.com/hql123/vue-ruby-china">vue-ruby-china</a> ★86 - VueJS框架搭建的rubychina平台</li>
<li><a href="https://github.com/monkeyWangs/doubanMovie-SSR">doubanMovie-SSR</a> ★85 - Vue豆瓣电影服务端渲染</li>
<li><a href="https://github.com/huangche007/vue-jd">vue-jd</a> ★76 - 京东移动web商城</li>
<li><a href="https://github.com/zimplexing/vue-nReader">vue-nReader</a> ★73 - 使用vue2.0 + vue-router + vuex 的一个多页面小说阅读webapp</li>
<li><a href="https://github.com/FatDong1/VueBlog">VueBlog</a> ★73 - 前后端分离的个人博客</li>
<li><a href="https://github.com/littlewin-wang/Zhihu_Daily">Zhihu_Daily</a> ★73 - 基于Vue和Nodejs的Web单页应用</li>
<li><a href="https://github.com/sinner77/vue-koa2-login">vue-koa2-login</a> ★67 - 使用 VueJS &amp; NodeJS 实现的登录注册</li>
<li><a href="https://github.com/houbx/webApp">webApp</a> ★64 - Vue2的移动端webApp音乐播放器</li>
<li><a href="https://github.com/wenye123/vue-trip">vue-trip</a> ★64 - vue2做的出行webapp</li>
<li><a href="https://github.com/Alex-xd/seeMusic">seeMusic</a> ★63 - 跨平台云音乐播放器</li>
<li><a href="https://github.com/SidKwok/github-explorer">github-explorer</a> ★63 - 寻找最有趣的GitHub库</li>
<li><a href="https://github.com/zhoou/vue-cli-multipage-bootstrap">vue-cli-multipage-bootstrap</a> ★60 - 将vue官方在线示例整合到组件中</li>
<li><a href="https://github.com/beautifulBoys/vue-XiaoMi-Shop">vue-XiaoMi-Shop</a> ★59 - 高仿小米商城的项目</li>
<li><a href="https://github.com/leehomeok/Vue-NetEaseCloudMusic">Vue-NetEaseCloudMusic</a> ★59 - 模仿IOS版网易云音乐的手机网站</li>
<li><a href="https://github.com/shaqihe/life-app-vue">life-app-vue</a> ★59 - 使用vue2完成多功能集合到小webapp</li>
<li><a href="https://github.com/MrMoveon/doubanApp">doubanApp</a> ★55 - 用vue2实现仿豆瓣app</li>
<li><a href="https://github.com/QRL909109/ios7-vue">ios7-vue</a> ★52 - 使用vue2.0 vue-router vuex模拟ios7</li>
<li><a href="https://github.com/hzzly/canvas-vue">canvas-vue</a> ★50 - 一个Vue+Cnavas酷炫后台管理</li>
<li><a href="https://github.com/nswbmw/vue-bushishiren">vue-bushishiren</a> ★49 - 不是诗人应用</li>
<li><a href="https://github.com/albertchan/vue-ssr-boilerplate">vue-ssr-boilerplate</a> ★48 - 精简版的ofvue-hackernews-2</li>
<li><a href="https://github.com/gaohongwei11/vuecommunity">vuecommunity</a> ★47 - vue.js中文社区</li>
<li><a href="https://github.com/pluto1114/vue-music163">vue-music163</a> ★47 - 音乐VueJS项目</li>
<li><a href="https://github.com/safaring/Vue2-MV">Vue2-MV</a> ★45 - 仿网易云音乐MV的webapp</li>
<li><a href="https://github.com/hua1995116/musiccloudWebapp">musiccloudWebapp</a> ★44 - 用vuejs仿网易云音乐</li>
<li><a href="https://github.com/BubblyPoker/cnode-vue">cnode-vue</a> ★40 - 基于vue和vue-router构建的cnodejs web网站SPA</li>
<li><a href="https://github.com/tyllo/Framework7-VueJS">Framework7-VueJS</a> ★38 - 使用移动框架的示例</li>
<li><a href="https://github.com/JerryYgh/m-eleme">m-eleme</a> ★37 - 基于Vue全家桶仿饿了么移动端webapp</li>
<li><a href="https://github.com/sailengsi/sls-vuex2-demo">sls-vuex2-demo</a> ★37 - vuex2商城购物车demo</li>
<li><a href="https://github.com/silianpan/eagles">eagles</a> ★36 - 各种组件封装</li>
<li><a href="https://github.com/fishenal/Todos_Vuejs">Todos_Vuejs</a> ★35 - vuejs2搭建的极简的todolist</li>
<li><a href="https://github.com/jiananle/vue-cnode">vue-cnode</a> ★35 - 用 Vue 做的 CNode 官网</li>
<li><a href="https://github.com/GitaiQAQ/HyaReader">HyaReader</a> ★35 - 移动友好的阅读器</li>
<li><a href="https://github.com/lanux/Vue-Admin">Vue-Admin</a> ★33 - 基于Vue2的Admin系统</li>
<li><a href="https://github.com/liupeijun/vue2-hybridapp-haoshiqi">vue2-hybridapp-haoshiqi</a> ★32 - 实现单页面webapp以及hybridapp</li>
<li><a href="https://github.com/xrr2016/zhihu-daily">zhihu-daily</a> ★32 - 轻松查看知乎日报内容</li>
<li><a href="https://github.com/xandeer/gank">gank</a> ★32 - gankio资源的阅读应用</li>
<li><a href="https://github.com/NewsNIng/vue-h5plus">vue-h5plus</a> ★31 - 前卫的vue及html5plus跨平台demo</li>
<li><a href="https://github.com/soulcm/vue-cnode-mobile">vue-cnode-mobile</a> ★29 - 搭建cnode社区</li>
<li><a href="https://github.com/alanWongsGithub/vue-weather">vue-weather</a> ★26 - 基于vue.js 2.0的百度天气应用</li>
<li><a href="https://github.com/doterlin/vue-user-center">vue-user-center</a> ★26 - vuejs直播类应用web端个人中心</li>
<li><a href="https://github.com/moonou/zhihu-daily-vue">zhihu-daily-vue</a> ★22 - 知乎日报</li>
<li><a href="https://github.com/Damonlw/vue-cnode">vue-cnode</a> ★22 - 使用cNode社区提供的接口</li>
<li><a href="https://github.com/BosNaufal/vue-starter">vue-starter</a> ★22 - VueJs项目的简单启动页</li>
<li><a href="https://github.com/wx1993/node-vue-fabaocn">node-vue-fabaocn</a> ★21 - 基于 node 和 vue 实现的移动官网</li>
<li><a href="https://github.com/youknowznm/vue-memo">vue-memo</a> ★20 - 用 vue写的记事本应用</li>
<li><a href="https://github.com/Halfeld/v-notes">v-notes</a> ★20 - 简单美观的记事本</li>
<li><a href="https://github.com/momopig/vue-flexible-app">vue-flexible-app</a> ★19 - vue开发的一个简易app</li>
<li><a href="https://github.com/CaiYiLiang/simply-calculator-vuejs">simply-calculator-vuejs</a> ★19 - 用VueJS实现简易计算器</li>
<li><a href="https://github.com/ITCNZ/vue-dropload">vue-dropload</a> ★19 - 用以测试下拉加载与简单路由</li>
<li><a href="https://github.com/fishenal/Vuejs-SalePlatform">Vuejs-SalePlatform</a> ★19 - vuejs搭建的售卖平台demo</li>
<li><a href="https://github.com/hj624608494/vue-shopping-mall">vue-shopping-mall</a> ★16 - 基于Vue.js 2.x系列 + vue2-router + axios + iview 商城</li>
<li><a href="https://github.com/yangbo5207/qqmusic">qqmusic</a> ★13 - QQ音乐vue</li>
<li><a href="https://github.com/deshes/vue-weather">vue-weather</a> ★12 - VueJS天气demo</li>
</ul>`;

const data = {
  title,
  content
};

export default data
